import { UserLoggedInProvider } from "@/context/IsLoggedIn.context";
import "../globals.css";
import AuthProtected from "@/components/auth/AuthProtected";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full">
          <UserLoggedInProvider>
            <AuthProtected>{children}</AuthProtected>
          </UserLoggedInProvider>
        </div>
      </body>
    </html>
  );
}
